# Generated by Django 4.1.7 on 2023-03-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('Country', models.CharField(max_length=100)),
                ('id_proof', models.FileField(upload_to='./idproof')),
            ],
        ),
    ]
