# Generated by Django 4.1.7 on 2023-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_id_type_id_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_data',
            name='id_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='id_data',
            name='id_fulldata',
            field=models.TextField(),
        ),
    ]
