# Generated by Django 4.1.7 on 2023-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_id_data_id_no_alter_id_data_id_fulldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_data',
            name='id_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
