# Generated by Django 4.1.7 on 2023-03-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_id_data_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_data',
            name='id_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
