# Generated by Django 4.1.7 on 2023-03-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_id_data_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_data',
            name='id_no',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
