# Generated by Django 4.1.7 on 2023-03-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_id_data_id_dob_alter_id_data_id_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_data',
            name='id_dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='id_data',
            name='id_fulldata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='id_data',
            name='id_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='id_data',
            name='id_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
